### ISSUE TITLE
bug: @returns does not respect jsdocUseColumns false

### ISSUE THREAD

**Issue by shunkica** [homer0/prettier-plugin-jsdoc#3]
Here is the related fixture:

```
module.exports = {
  only: true,
  jsdocPrintWidth: 95,
  jsdocUseColumns: false,
};

//# input

/**
 * @param {foo} bar baz
 * @returns {number} Returns how the node is positioned relatively to the reference node
 * according to the bitmask. 0 if reference node and given node are the same.
 */

//# output

/**
 * @param {foo} bar
 * Baz.
 * @returns {number}
 * Returns how the node is positioned relatively to the reference node according to the
 * bitmask. 0 if reference node and given node are the same.
 */

```

The actual output is:

```
/**
 * @param {foo} bar
 * Baz.
 * @returns {number} Returns how the node is positioned relatively to the reference node
 *                   according to the bitmask. 0 if reference node and given node are the same.
 */
```

**Comment by shunkica** [comment]
The problem seems to be that the description of `@returns` gets placed in the `name` property instead of the `description` property, but `@returns` [shouldn't have a `name` property](https://jsdoc.app/tags-returns.html).

**Comment by shunkica** [comment]
The issue seems to originate from [comment-parser](https://github.com/syavorsky/comment-parser)

It is already reported [here](https://github.com/syavorsky/comment-parser/issues/144)
There is a possible workaround mentioned, and no plan to fix this behavior has been announced.

**Comment by homer0** [comment]
@shunkica thanks for tracking it down :D. `@returns` is not the only tag with that issue, and I already have workarounds in place for cases with no description, no name, or description split between name and description.

For some reason, it seems like I intentionally wanted the description of the `@returns` to match the description of the `@param`s, on column mode, so I had it on the wrong group.

Since, I believe, you are still using v6, a workaround to get this fix would be to [follow these instructions to extend the plugin](https://github.com/homer0/prettier-plugin-jsdoc#%EF%B8%8F-modifying-the-functionality), and override `getTagsWithDescriptionAsName` && `getTagsWithNameAsDescription` to match the changes [in this commit](https://github.com/homer0/prettier-plugin-jsdoc/pull/6/commits/1dc8632a0f3d434cf3a60805f05a848124c0c509).

**Comment by shunkica** [comment]
Thanks for the response. We have moved to v7 since so it should be good once you release a fix.
