### ISSUE TITLE
feature request: Add option to force inline descriptions

### ISSUE THREAD

**Issue by shunkica** [homer0/prettier-plugin-jsdoc#4]
### Summary:

Add an option that allows descriptions to remain inline when `jsdocUseColumns` is set to false.

Currently, the library dafaults to formatting tag types, names, descriptions into columns. While there is an option to turn off this behavior (`jsdocUseColumns` set to false), doing so automatically moves all the descriptions to new lines.

This feature request aims to introduce a new configuration option that will enable users to force inline descriptions.

### Current Behavior:

When `jsdocUseColumns` is set to false, all the descriptions are forced to new lines, regardless of the length or format of the content.

### Proposed Feature:

Introduce a new configuration option, for example `jsdocKeepDescriptionsInline`, which will ensure descriptions remain inline, regardless of the `jsdocUseColumns` setting. This will give users more control over the formatting of their JSdoc comments.

When `jsdocKeepDescriptionsInline` is set to true, the expected behavior is as follows:

```
@param {foobar} baz description of prop 1
@param {foo} barbaz description of prop 2
```

As far as I can tell the option should have no effect on rendering when `jsdocUseColumns` is set to true.

### Benefits:

    Provides users with more control over the formatting of JSdoc comments.
    Eliminates excessive whitespace created by column formatting while maintaining the readability of inline descriptions.
    Adds flexibility for users who want descriptions to remain inline, even when column formatting is disabled.

**Comment by homer0** [comment]
Hey @shunkica!

I'm so sorry it took me so much time to get back to you... a lot of things happened and completely forgot about this.

In case you are still interested in this: I understand the motivation for that proposal, there are cases where you don't want the plugin to act, but for that, I'd recommend `@prettierignore` rather than an extra option that would mess with rendering. You see the issue in `@params`, but the rules for columns and that stuff apply to ALL the tags.

Given that I tried to make it REAAAALLY flexible, when messing with the rendering, there are a lot of options that come in to play, so, no, I won't be adding a `jsdocKeepDescriptionsInline` (at least not now), but... I did something quick that I hope can help you with your particular scenario: [`jdocIgnoreTags`](https://github.com/homer0/prettier-plugin-jsdoc?tab=readme-ov-file#ignore-specific-tags).

I know it's not the same, but you can use it to specify tags that you don't want to format. You can check #10 and see the added fixtures with example cases.

Again, sorry for the delay (and the answer)
Regards.
