### ISSUE TITLE
feature request: allow free text after @since

### ISSUE THREAD

**Issue by shunkica** [homer0/prettier-plugin-jsdoc#5]
### Summary:

Extend flexibility to accept any text following the `@since` tag, not just version numbers.

The current behavior of the library enforces the `@since` tag to be followed by a version number. Any text after the tag that isn't recognized as a version number is automatically moved to a new line. This isn't accommodating for cases where the @since tag needs to be followed by descriptors other than version numbers (e.g., `@since DOM L3 Core`).

### Current Behavior:

If the @since tag is followed by multiple words, the remaining text is pushed to a new line, like so:

```
@since DOM
L3 Core
```

### Proposed Feature:

Option 1. Introduce a new configuration option, for example `jsdocAllowSinceText`, that would allow any text to follow the `@since `tag and remain on the same line.

Option 2. Allow any text to follow `@since` by default

The expected behavior would be as follows:

`@since DOM L3 Core`

### Benefits:

    Provides greater flexibility in using the @since tag, accommodating a wider range of use cases.

**Comment by homer0** [comment]
This is similar to the solution I mentioned in #3; I just had to move `@since` to the `getTagsWithNameAsDescription` group, and _since_ the `name` is never pushed to a new line, it's always next to the tag :).

You can get it on v6 by overriding `getTagsWithNameAsDescription` and adding it to the list, but... I added an extra fix that won't be so easy to bring to v6: It didn't make sense to add the sentence formatting (Uppercase & period at the end) to `@since`, so I added a new constant and check for tags where the formatting shouldn't happen.

[Here's the commit if you want to replicate it](https://github.com/homer0/prettier-plugin-jsdoc/pull/6/commits/1d4167b8ff48b8166e05b63004d199c77b55d43e).
